#!/bin/bash
file=polythore_popgen.vcf
#create a file with the number of SNPs per locus, replace the awk number by the number of header lines
grep "#" $file > random_vcf.vcf
lines=$(wc -l random_vcf.vcf | cut -f 1 -d " ")
#calculate the repetitions per locus
cut -f 1 $file | awk -v var=$lines 'NR > var' | sort | uniq -c | sed -E 's/^\s+(\w+)/\1/g' > counts_by_loci.txt

N=10
#select randon one nucleotide
for k in $(echo {1..100}); do
((i=i%N)); ((i++==0)) && wait
grep "#" $file > random_$k.vcf
cat counts_by_loci.txt | while read i; do
locus=$(grep "$i" counts_by_loci.txt | cut -d " " -f 2)
grep "$locus" $file | shuf -n 1 >> random_$k.vcf;done;done
